credentials:
  usernames:
    jsmith:
      email: jsmith@gmail.com
      name: John Smith
      password: $2b$12$KujTAegFHLK5bLTHAP9tLeXElnSt934IsGHr8gc8HaZSreDdkJ9r6
    rbriggs:
      email: rbriggs@gmail.com
      name: Rebecca Briggs
      password:  $2b$12$/22vdFs1W4WsUzvHRNxMqOChOtLmVW1ouTb/uAx6UJZurAHvLR5x.
cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
preauthorized:
  emails:
  - melsby@gmail.com